import type { McqPairConfig } from "@/lib/tests/mcqPair";

export const ARTICLES: McqPairConfig = {
  id: "articles",
  slug: "articles",
  href: "/tests/articles",
  accent: "steel",
  eyebrow: "Round 7 · Grammar drill",
  titleLead: "The ",
  titleEm: "Article",
  titleTail: " of the Matter",
  lede: "Hindi and Telugu don't have articles at all — which is exactly why \"a,\" \"an,\" \"the,\" and no article are the single most common daily slip in Indian English. The rules are tight. This drill locks them in.",
  howto: [
    "<b>Part I — Fill the gap.</b> Each sentence has a blank. Choose \"a,\" \"an,\" \"the,\" or \"no article\" — whichever the sentence actually needs.",
    "<b>Part II — Pick the correct sentence.</b> All four options are the same sentence with only the article changed. Pick the one that's actually right.",
    "<b>Scoring:</b> each item is worth 1 point, 32 total.",
  ],
  part1: {
    title: "Fill the gap",
    note: "Choose the article that belongs in the blank.",
    items: [
      { sentence: "She sent ___ email to the whole team yesterday.", options: ["a", "an", "the", "no article"], correct: 1, why: "First mention of something unspecified — and “email” starts with a vowel sound, so it takes “an.”" },
      { sentence: "The email you sent yesterday was very clear. I replied to ___ email right away.", options: ["a", "an", "the", "no article"], correct: 2, why: "Second mention of the same, now-specific email — “the” points back to it." },
      { sentence: "He is ___ best developer on our team.", options: ["a", "an", "the", "no article"], correct: 2, why: "Superlatives (“best,” “tallest,” “most senior”) always take “the.”" },
      { sentence: "___ sun sets earlier in December.", options: ["a", "an", "the", "no article"], correct: 2, why: "There's only one sun — unique things in the world take “the.”" },
      { sentence: "We need ___ feedback before finalizing the report.", options: ["a", "an", "the", "no article"], correct: 3, why: "“Feedback” is uncountable and unspecified here — no article." },
      { sentence: "___ meetings at this company always start on time.", options: ["a", "an", "the", "no article"], correct: 3, why: "A generic plural (meetings in general) takes no article." },
      { sentence: "He is still in ___ college, finishing his final year.", options: ["a", "an", "the", "no article"], correct: 3, why: "“In college” meaning “a student” is the institution used for its general purpose — no article." },
      { sentence: "Please meet me at ___ college near the railway station — I'll be waiting outside.", options: ["a", "an", "the", "no article"], correct: 2, why: "Here “college” means one specific building, not the general idea of being a student — that takes “the.”" },
      { sentence: "She plays ___ guitar every evening after work.", options: ["a", "an", "the", "no article"], correct: 2, why: "Musical instruments after “play” conventionally take “the”: the guitar, the piano, the violin." },
      { sentence: "We usually have ___ lunch at 1 PM in the cafeteria.", options: ["a", "an", "the", "no article"], correct: 3, why: "Meals (breakfast, lunch, dinner) take no article in general statements." },
      { sentence: "He has ___ headache and needs to leave early today.", options: ["a", "an", "the", "no article"], correct: 0, why: "Common minor ailments like a headache, a cold, a fever are countable and take “a.”" },
      { sentence: "They are relocating to ___ United States next month for the new office.", options: ["a", "an", "the", "no article"], correct: 2, why: "Country names that are unions, republics, or plural in form (the United States, the UK, the Netherlands) take “the.”" },
      { sentence: "She recently visited ___ India for a client conference.", options: ["a", "an", "the", "no article"], correct: 3, why: "Most single country names take no article: India, France, Japan." },
      { sentence: "It took ___ hour to finish reviewing the contract.", options: ["a", "an", "the", "no article"], correct: 1, why: "“Hour” starts with a silent h — the sound is a vowel, so it takes “an.”" },
      { sentence: "He's ___ European client, so the call is scheduled for the morning IST.", options: ["a", "an", "the", "no article"], correct: 0, why: "“European” is spelled with a vowel but starts with a consonant sound (“yuro-”), so it takes “a,” not “an.”" },
      { sentence: "This is ___ third time she has missed the deadline this month.", options: ["a", "an", "the", "no article"], correct: 2, why: "Ordinal numbers (first, second, third) take “the.”" },
      { sentence: "He works as ___ project manager at the firm.", options: ["a", "an", "the", "no article"], correct: 0, why: "An indefinite role — one of possibly many project managers — takes “a.”" },
      { sentence: "She is ___ CEO of the company — there's only one.", options: ["a", "an", "the", "no article"], correct: 2, why: "A unique role (only one person holds it) takes “the.”" },
      { sentence: "___ honesty is valued highly in this organization.", options: ["a", "an", "the", "no article"], correct: 3, why: "An abstract, uncountable noun used in a general sense takes no article." },
      { sentence: "___ honesty you showed in that meeting really impressed the client.", options: ["a", "an", "the", "no article"], correct: 2, why: "The same abstract noun, now made specific by “you showed in that meeting,” takes “the.”" },
    ],
  },
  part2: {
    title: "Pick the correct sentence",
    note: "All four options are the same sentence with only the article changed. Pick the one that's right.",
    items: [
      { sentence: "", options: ["She is best candidate for the role.", "She is a best candidate for the role.", "She is the best candidate for the role.", "She is an best candidate for the role."], correct: 2, why: "Superlatives always take “the” — never “a/an,” and never no article." },
      { sentence: "", options: ["He gave a excellent presentation yesterday.", "He gave an excellent presentation yesterday.", "He gave the excellent presentation yesterday.", "He gave excellent presentation yesterday."], correct: 1, why: "First mention, indefinite — and “excellent” starts with a vowel sound, so it's “an.”" },
      { sentence: "Thanks for the call earlier.", options: ["Can you send me information you mentioned?", "Can you send me an information you mentioned?", "Can you send me the information you mentioned?", "Can you send me a information you mentioned?"], correct: 2, why: "“Information” is uncountable, so “a/an information” is never correct — and here it's already specific (“you mentioned”), so it needs “the.”" },
      { sentence: "", options: ["I need advice from an expert.", "I need advice from a expert.", "I need advice from the expert.", "I need an advice from an expert."], correct: 0, why: "“Advice” is uncountable — no article. “Expert” is countable, unspecified, and starts with a vowel sound, so it takes “an.”" },
      { sentence: "We hired a new developer last month.", options: ["A developer is doing great work so far.", "An developer is doing great work so far.", "The developer is doing great work so far.", "Developer is doing great work so far."], correct: 2, why: "Second mention of the same person, now specific — “the developer.”" },
      { sentence: "", options: ["He has a great deal of experience in this field.", "He has an great deal of experience in this field.", "He has the great deal of experience in this field.", "He has great deal of experience in this field."], correct: 0, why: "“A great deal of” is a fixed idiom — it always takes “a,” regardless of what follows it." },
      { sentence: "The client just emailed their invoice.", options: ["Please forward a invoice to the accounts team.", "Please forward an invoice to the accounts team.", "Please forward the invoice to the accounts team.", "Please forward invoice to the accounts team."], correct: 2, why: "A specific invoice was just mentioned — refer back to it with “the.”" },
      { sentence: "", options: ["He is the only person who reviewed the contract.", "He is a only person who reviewed the contract.", "He is an only person who reviewed the contract.", "He is only person who reviewed the contract."], correct: 0, why: "“The only” is a fixed pairing — “only” as this kind of limiting adjective always takes “the.”" },
      { sentence: "", options: ["It took a hour to finish the review.", "It took an hour to finish the review.", "It took the hour to finish the review.", "It took hour to finish the review."], correct: 1, why: "“Hour” starts with a silent h — a vowel sound — so it takes “an.”" },
      { sentence: "", options: ["They relocated to United States last year.", "They relocated to a United States last year.", "They relocated to the United States last year.", "They relocated to an United States last year."], correct: 2, why: "“The United States” — country names that are unions or plural in form take “the.”" },
      { sentence: "", options: ["She visited a India for a conference last month.", "She visited an India for a conference last month.", "She visited the India for a conference last month.", "She visited India for a conference last month."], correct: 3, why: "Single country names like India take no article." },
      { sentence: "", options: ["Please note the meetings are usually scheduled for Monday mornings.", "Please note meetings are usually scheduled for Monday mornings.", "Please note a meetings are usually scheduled for Monday mornings.", "Please note an meetings are usually scheduled for Monday mornings."], correct: 1, why: "A generic plural (meetings in general, not a specific set) takes no article." },
    ],
  },
  bands: [
    { max: 40, code: "Shaky", name: "Still guessing", desc: "Regularly drops articles or adds one where none belongs — the two most common slips for Hindi/Telugu speakers. Drill the core split (specific = “the,” first mention = “a/an,” general = nothing) before anything else." },
    { max: 65, code: "Developing", name: "Getting there", desc: "Reliable on plain first-mention/back-reference cases but slips on the trickier rules — superlatives, unique roles, and sound-based a/an." },
    { max: 85, code: "Solid", name: "Reliable", desc: "Consistently correct across most categories, with only occasional slips on idioms and less common country-name rules." },
    { max: 100, code: "Native-like", name: "Automatic", desc: "Handles even the classic traps — the United States vs. India, an hour vs. a European — without hesitation." },
  ],
  ladder: [
    ["Shaky", "Still guessing"],
    ["Developing", "Getting there"],
    ["Solid", "Reliable"],
    ["Native-like", "Automatic"],
  ],
  ladderEnds: ["Shaky", "Native-like"],
  tiles: { labels: ["Fill the gap", "Pick the sentence"] },
  footNote:
    "Each item has exactly one correct answer, tied to a specific article rule — check the review to see which rule you missed.",
};
