import type { McqPairConfig } from "@/lib/tests/mcqPair";

export const CORPORATE_CONFUSION: McqPairConfig = {
  id: "corporate-confusion",
  slug: "corporate-confusion",
  href: "/tests/corporate-confusion",
  accent: "steel",
  eyebrow: "Round 8 · Corporate English",
  titleLead: "The ",
  titleEm: "Corporate",
  titleTail: " Confusion",
  lede: "\"Revert back,\" \"discuss about,\" \"kindly do the needful\" — the padded phrases that instantly flag an email as non-native. Plus the word pairs that look alike, sound alike, and get swapped constantly: affect/effect, its/it's, loose/lose.",
  howto: [
    "<b>Part I — Cut the redundancy.</b> Four versions of the same sentence. Pick the one that says it without padding or doubling up.",
    "<b>Part II — Confusable words.</b> Pick the word that actually belongs in the blank.",
    "<b>Scoring:</b> each item is worth 1 point, 30 total.",
  ],
  part1: {
    title: "Cut the redundancy",
    note: "Pick the version that says it without padding or doubling up.",
    items: [
      { options: ["Please revert to me by end of day.", "Please revert back to me by end of day.", "Please revert back with me by end of day.", "Please back-revert to me by end of day."], correct: 0, why: "“Revert” already means “reply back” — “revert back” doubles up the same meaning." },
      { options: ["Let's discuss about the budget in tomorrow's call.", "Let's discuss the budget in tomorrow's call.", "Let's discuss on the budget in tomorrow's call.", "Let's discuss about of the budget in tomorrow's call."], correct: 1, why: "“Discuss” is already transitive (“discuss X”) — adding “about” is redundant." },
      { options: ["Kindly do the needful at the earliest.", "Kindly do the needful and revert back at the earliest.", "Please complete this by Friday.", "Please do the needful thing at the earliest."], correct: 2, why: "“Do the needful” is vague filler — state the actual action and the actual deadline." },
      { options: ["Please find attached herewith the report.", "Attached herewith, please find the report.", "Herewith attached please find the report.", "Please find the report attached."], correct: 3, why: "“Herewith” and “attached” both already signal the same thing — pick one, or neither." },
      { options: ["This is essential for the launch.", "This is absolutely essential for the launch.", "This is absolutely very essential for the launch.", "This is completely absolutely essential for the launch."], correct: 0, why: "“Essential” already means necessary — “absolutely” adds nothing." },
      { options: ["We need to completely eliminate all errors before shipping.", "We need to eliminate all errors before shipping.", "We need to completely remove and eliminate all errors before shipping.", "We need to totally completely eliminate all errors before shipping."], correct: 1, why: "“Eliminate” already means to remove entirely — “completely” is redundant." },
      { options: ["Each and every team member must complete the training.", "Each and every single team member must complete the training.", "Each team member must complete the training.", "Every each team member must complete the training."], correct: 2, why: "“Each” and “every” cover the same ground — use one, not both." },
      { options: ["The final outcome of the project exceeded expectations.", "The final end outcome of the project exceeded expectations.", "The final result outcome of the project exceeded expectations.", "The outcome of the project exceeded expectations."], correct: 3, why: "“Outcome” is already the result — “final” adds nothing new." },
      { options: ["We need additional headcount to meet the Q4 targets.", "We need additional headcount in order to meet the Q4 targets.", "We need additional headcount in order that we meet the Q4 targets.", "We need additional headcount for the purpose of meeting the Q4 targets."], correct: 0, why: "“In order to” is a wordy stand-in for “to” before a verb." },
      { options: ["The new hire brought an added bonus of language skills to the team.", "The new hire brought a bonus of language skills to the team.", "The new hire brought an added extra bonus of language skills to the team.", "The new hire brought an additional added bonus of language skills to the team."], correct: 1, why: "A “bonus” is already something extra — “added” is redundant." },
      { options: ["With regard to the budget, we'll finalize numbers next week.", "With regards to the budget, we'll finalize numbers next week.", "Regarding the budget, we'll finalize numbers next week.", "In regard to the budget, we'll finalize numbers next week."], correct: 2, why: "“Regarding” alone replaces the wordier “with regard to” / “in regard to” — and “with regards to” (plural) is a common error on top of the wordiness." },
      { options: ["Please use the exact same template for all client decks.", "Please use the exact template for all client decks.", "Please use the same exact identical template for all client decks.", "Please use the same template for all client decks."], correct: 3, why: "“Same” alone already means identical — “exact same” is redundant, however common it sounds." },
      { options: ["Right now, we don't have budget approval.", "At this point in time, we don't have budget approval.", "At this moment in time, we don't have budget approval.", "At this current point in time, we don't have budget approval."], correct: 0, why: "“At this point in time” is a wordy stand-in for “now” or “right now.”" },
      { options: ["The two offices are in close proximity to each other.", "The two offices are in proximity to each other.", "The two offices are in close and near proximity to each other.", "The two offices are in near proximity to each other."], correct: 1, why: "“Proximity” already means closeness — “close proximity” is redundant, though very common in speech." },
      { options: ["Due to the fact that the vendor delayed shipping, we missed the deadline.", "Due to the fact of the vendor delaying shipping, we missed the deadline.", "Because the vendor delayed shipping, we missed the deadline.", "Owing to the fact that the vendor delayed shipping, we missed the deadline."], correct: 2, why: "“Due to the fact that” is a wordy stand-in for “because.”" },
    ],
  },
  part2: {
    title: "Confusable words",
    note: "Pick the word that actually belongs in the blank.",
    items: [
      { sentence: "The new pricing policy will directly ___ our margins.", options: ["affect", "effect", "effected", "affection"], correct: 0, why: "“Affect” is the verb — it means “to influence.”" },
      { sentence: "The ___ of the policy change won't be visible until next quarter.", options: ["affect", "effect", "effective", "affected"], correct: 1, why: "“Effect” is the noun here — it means “a result.”" },
      { sentence: "___ presentation was rescheduled to Thursday.", options: ["It's", "There", "Its", "Its'"], correct: 2, why: "“Its” is the possessive form — no apostrophe." },
      { sentence: "___ time to send out the updated schedule.", options: ["Its", "There", "Its'", "It's"], correct: 3, why: "“It's” is the contraction of “it is.”" },
      { sentence: "She's a better presenter ___ I am.", options: ["than", "then", "them", "that"], correct: 0, why: "“Than” is used for comparisons." },
      { sentence: "We finished the review, and ___ we moved to sign-off.", options: ["than", "then", "them", "that"], correct: 1, why: "“Then” marks a sequence in time — “after that.”" },
      { sentence: "Please don't ___ the deadline again — we can't slip further.", options: ["loose", "loss", "lose", "lost"], correct: 2, why: "“Lose” is the verb — “to fail to meet or keep.”" },
      { sentence: "The screws on the server rack are ___ and need tightening.", options: ["lose", "loss", "lost", "loose"], correct: 3, why: "“Loose” is the adjective — “not tight.”" },
      { sentence: "The ___ reason for the delay was a vendor issue, not our team.", options: ["principal", "principle", "principled", "principals"], correct: 0, why: "“Principal” as an adjective means “main” or “primary.”" },
      { sentence: "We operate on the ___ of transparency with every client.", options: ["principal", "principle", "principled", "principals"], correct: 1, why: "“Principle” is the noun for a fundamental rule or belief." },
      { sentence: "Her presentation nicely ___ the data we shared earlier.", options: ["compliments", "complementary", "complements", "complimentary"], correct: 2, why: "“Complements” (with an e) means “completes” or “goes well with.”" },
      { sentence: "The client sent a ___ about how smooth the rollout was.", options: ["complement", "complementary", "complimenting", "compliment"], correct: 3, why: "“Compliment” (with an i) is the noun for praise." },
      { sentence: "We're out of printer paper — someone needs to order more ___.", options: ["stationery", "stationary", "stationed", "stationing"], correct: 0, why: "“Stationery” (with an e) refers to writing and office supplies." },
      { sentence: "The delivery van has been ___ outside the building for an hour.", options: ["stationery", "stationary", "stationed", "station"], correct: 1, why: "“Stationary” (with an a) means “not moving.”" },
      { sentence: "We need ___ information before we can approve the budget.", options: ["farther", "father", "further", "furthest"], correct: 2, why: "“Further” is used for additional or abstract extent; “farther” is reserved for physical distance." },
    ],
  },
  bands: [
    { max: 40, code: "Shaky", name: "Still guessing", desc: "Padded phrases like “revert back” and “discuss about” slip through often, and the confusable pairs (its/it's, loose/lose) are still a coin flip. Drill the fixed redundancy list first — it's the fastest fix." },
    { max: 65, code: "Developing", name: "Getting there", desc: "Catches the most obvious redundancies but still doubles up on the subtler ones, and mixes up word pairs under time pressure." },
    { max: 85, code: "Solid", name: "Reliable", desc: "Writes cleanly most of the time, with only occasional slips on the less common redundant phrases or a rushed word-pair mix-up." },
    { max: 100, code: "Native-like", name: "Automatic", desc: "Cuts the padding by instinct and never confuses affect/effect, its/it's, or loose/lose." },
  ],
  ladder: [
    ["Shaky", "Still guessing"],
    ["Developing", "Getting there"],
    ["Solid", "Reliable"],
    ["Native-like", "Automatic"],
  ],
  ladderEnds: ["Shaky", "Native-like"],
  tiles: { labels: ["Redundancy", "Confusable words"] },
  footNote: "Each item has exactly one correct answer — check the review to see the rule behind it.",
};
