import type { GrammarCourtConfig } from "@/lib/tests/grammarCourt";

export const GRAMMAR_COURT: GrammarCourtConfig = {
  id: "grammar-court",
  slug: "grammar-court",
  href: "/tests/grammar-court",
  eyebrow: "Pro · AI-graded bonus",
  titleLead: "Grammar ",
  titleEm: "Court",
  titleTail: " is in session",
  lede: "20 real workplace phrases. Some are clean, some are guilty. Deliver your verdict — and for anything you convict, name the crime and file the fix for a bonus point.",
  howto: [
    "<b>Read each phrase.</b> Some are perfectly fine as written; others have a real grammar or word-usage slip. Decide which.",
    "<b>Pick Correct or Incorrect.</b> A right call is worth +1, a wrong call costs you -1 — no free passes.",
    "<b>Convicted one?</b> Name the issue and write the fix for a shot at a bonus point. Get the explanation wrong and nothing extra is deducted, so it's always worth a try.",
  ],
  promptKey: "grammar-court-eval",
  bands: [
    { max: 40, code: "D", name: "Held in Contempt", desc: "Verdicts are a coin flip and the case notes don't help — grammar instincts need real work." },
    { max: 65, code: "C", name: "Case Pending", desc: "Spots the obvious slips but the trickier ones get through, and the fixes aren't landing yet." },
    { max: 85, code: "B", name: "Sound Judgment", desc: "Calls it right most of the time and usually nails the fix when it matters." },
    { max: 100, code: "A", name: "Chief Justice", desc: "Sharp verdicts and airtight corrections — nothing gets past this bench." },
  ],
  items: [
    {
      phrase: "The team have completed the sprint on time.",
      correct: false,
      issue: "Subject-verb agreement — \"team\" is treated as a singular unit here, so it needs \"has\", not \"have\".",
      fix: "The team has completed the sprint on time.",
    },
    {
      phrase: "Please find the attached report for your review.",
      correct: true,
      issue: "",
      fix: "",
    },
    {
      phrase: "Please revert back to me by end of day.",
      correct: false,
      issue: "\"Revert\" already means to go back to a previous point, so \"revert back\" is redundant.",
      fix: "Please revert to me by end of day.",
    },
    {
      phrase: "We look forward to hearing from you soon.",
      correct: true,
      issue: "",
      fix: "",
    },
    {
      phrase: "She don't have access to the dashboard yet.",
      correct: false,
      issue: "Subject-verb agreement — \"she\" needs \"doesn't\", not \"don't\".",
      fix: "She doesn't have access to the dashboard yet.",
    },
    {
      phrase: "I would appreciate it if you could confirm the meeting time.",
      correct: true,
      issue: "",
      fix: "",
    },
    {
      phrase: "I am agree that the deadline should be extended.",
      correct: false,
      issue: "\"Agree\" is a verb, not an adjective — it can't follow \"am\". It should be used in the simple present on its own.",
      fix: "I agree that the deadline should be extended.",
    },
    {
      phrase: "The deployment has been scheduled for tomorrow morning.",
      correct: true,
      issue: "",
      fix: "",
    },
    {
      phrase: "He explained me the process yesterday.",
      correct: false,
      issue: "\"Explain\" needs \"to\" before an indirect object — you can't explain someone something directly.",
      fix: "He explained the process to me yesterday.",
    },
    {
      phrase: "Let me know if you have any questions.",
      correct: true,
      issue: "",
      fix: "",
    },
    {
      phrase: "We are discussing about the budget in today's call.",
      correct: false,
      issue: "\"Discuss\" is already transitive — it doesn't take \"about\" before its object.",
      fix: "We are discussing the budget in today's call.",
    },
    {
      phrase: "She has been leading this project since January.",
      correct: true,
      issue: "",
      fix: "",
    },
    {
      phrase: "The report was send to the client last week.",
      correct: false,
      issue: "Wrong past participle after \"was\" — the passive voice needs \"sent\", not \"send\".",
      fix: "The report was sent to the client last week.",
    },
    {
      phrase: "Could you please share the updated timeline by Friday?",
      correct: true,
      issue: "",
      fix: "",
    },
    {
      phrase: "Each of the developers have their own laptop.",
      correct: false,
      issue: "\"Each\" is singular, so the verb should be \"has\", not \"have\", regardless of the plural noun in between.",
      fix: "Each of the developers has their own laptop.",
    },
    {
      phrase: "The client raised a concern about the pricing structure.",
      correct: true,
      issue: "",
      fix: "",
    },
    {
      phrase: "I have went through the documentation already.",
      correct: false,
      issue: "Wrong past participle after \"have\" — it needs \"gone\", not \"went\".",
      fix: "I have gone through the documentation already.",
    },
    {
      phrase: "Please let me know if you have any query's.",
      correct: false,
      issue: "An apostrophe was used to form a plural — \"queries\" is the correct plural, no apostrophe needed.",
      fix: "Please let me know if you have any queries.",
    },
    {
      phrase: "The manager along with his team are attending the workshop.",
      correct: false,
      issue: "An \"along with...\" phrase doesn't change the number of the main subject — \"manager\" is singular, so the verb should be \"is\".",
      fix: "The manager along with his team is attending the workshop.",
    },
    {
      phrase: "Between you and I, this release is risky.",
      correct: false,
      issue: "\"Between\" is a preposition and takes the objective case, so it should be \"you and me\", not \"you and I\".",
      fix: "Between you and me, this release is risky.",
    },
  ],
};
