import type { McqPairConfig } from "@/lib/tests/mcqPair";

export const INCORRECTLY_CORRECT: McqPairConfig = {
  id: "incorrectly-correct",
  slug: "incorrectly-correct",
  href: "/tests/incorrectly-correct",
  accent: "rose",
  eyebrow: "Round 9 · Grammar & vocabulary",
  titleLead: "The ",
  titleEm: "Incorrectly Correct",
  titleTail: " Things",
  lede: "Two habits that sound fine in your head but aren't: putting stative verbs like \"know\" and \"want\" into the continuous (\"I am knowing\"), and pairing the wrong verb with a fixed noun (\"do a mistake\" instead of \"make a mistake\").",
  howto: [
    "<b>Part I — Stative verbs.</b> Pick the correct form of the verb in brackets. Most stative verbs never take the \"-ing\" form — but a few verbs change meaning and do take it, so read carefully.",
    "<b>Part II — Collocations.</b> All four options are the same sentence with only the word pairing changed. Pick the one that's actually how English is used.",
    "<b>Scoring:</b> each item is worth 1 point, 25 total.",
  ],
  part1: {
    title: "Stative verbs",
    note: "Pick the correct form of the verb in brackets.",
    items: [
      { sentence: "I ___ the answer already, so you don't need to explain again.", hint: "Verb: know", options: ["know", "am knowing", "knows", "was knowing"], correct: 0, why: "“Know” is a stative verb — a state of knowledge, not an action — so it never takes the continuous form." },
      { sentence: "She ___ to leave early today because of a doctor's appointment.", hint: "Verb: want", options: ["want", "wants", "is wanting", "was wanting"], correct: 1, why: "“Want” describes a state of desire, not an action — no continuous form, even for something happening today." },
      { sentence: "This laptop bag ___ to Priya, not to me.", hint: "Verb: belong", options: ["belong", "is belonging", "belongs", "was belonging"], correct: 2, why: "“Belong” describes a state of ownership, not an action — no continuous form." },
      { sentence: "He ___ the new policy yet — can you explain it again?", hint: "Verb: not understand", options: ["don't understand", "isn't understanding", "wasn't understanding", "doesn't understand"], correct: 3, why: "“Understand” is a mental state — never continuous, even when it's temporary." },
      { sentence: "We ___ your approval before we can proceed with the vendor contract.", hint: "Verb: need", options: ["need", "needs", "are needing", "was needing"], correct: 0, why: "“Need” is a state, not an action being performed — no continuous form." },
      { sentence: "I ___ this proposal is a great idea.", hint: "Verb: think", options: ["thinks", "think", "am thinking", "was thinking"], correct: 1, why: "Used to state an opinion or belief, “think” is stative here — no continuous form." },
      { sentence: "Right now, she ___ about how to respond to the client's email.", hint: "Verb: think", options: ["thinks", "think", "is thinking", "was thinking"], correct: 2, why: "Here “think about” describes an active mental process happening right now — this sense of “think” does take the continuous." },
      { sentence: "I ___ two meetings this afternoon.", hint: "Verb: have", options: ["has", "am having", "was having", "have"], correct: 3, why: "“Have” meaning possession or a fixed schedule is stative — no continuous form." },
      { sentence: "I can't talk right now — I ___ lunch with a client.", hint: "Verb: have", options: ["am having", "have", "has", "had"], correct: 0, why: "“Have” meaning “to eat” describes a dynamic action — this sense does take the continuous." },
      { sentence: "The proposal ___ reasonable, but let's review the numbers first.", hint: "Verb: seem", options: ["seem", "seems", "is seeming", "was seeming"], correct: 1, why: "“Seem” describes a state of appearing to be — never continuous." },
      { sentence: "This report ___ several errors that need fixing.", hint: "Verb: contain", options: ["contain", "is containing", "contains", "was containing"], correct: 2, why: "“Contain” describes a fixed property, not an action — no continuous form." },
      { sentence: "I ___ with the new remote-work policy.", hint: "Verb: not agree", options: ["doesn't agree", "am not agreeing", "wasn't agreeing", "don't agree"], correct: 3, why: "“Agree” is a state of shared opinion — no continuous form." },
      { sentence: "He ___ three properties in the city.", hint: "Verb: own", options: ["owns", "own", "is owning", "was owning"], correct: 0, why: "“Own” is a state of possession — no continuous form." },
    ],
  },
  part2: {
    title: "Collocations",
    note: "All four options are the same sentence with only the word pairing changed. Pick the one that's actually how English is used.",
    items: [
      { options: ["She made a mistake in the report.", "She did a mistake in the report.", "She took a mistake in the report.", "She had a mistake in the report."], correct: 0, why: "“Make a mistake” is the fixed collocation — “do/take/have a mistake” aren't standard English." },
      { options: ["You need to do more effort to meet the deadline.", "You need to make more effort to meet the deadline.", "You need to take more effort to meet the deadline.", "You need to give more effort to meet the deadline."], correct: 1, why: "“Make an effort” is the fixed collocation." },
      { options: ["Please make your homework before dinner.", "Please take your homework before dinner.", "Please do your homework before dinner.", "Please have your homework before dinner."], correct: 2, why: "“Do your homework” is the fixed collocation — “make/take/have homework” aren't standard." },
      { options: ["Could you make me a favor and forward this email?", "Could you take me a favor and forward this email?", "Could you give me a favor and forward this email?", "Could you do me a favor and forward this email?"], correct: 3, why: "“Do someone a favor” is the fixed collocation." },
      { options: ["The team is making good progress on the migration.", "The team is doing good progress on the migration.", "The team is taking good progress on the migration.", "The team is having good progress on the migration."], correct: 0, why: "“Make progress” is the fixed collocation — “do/take/have progress” aren't standard." },
      { options: ["After the outage, she stepped up and did full responsibility for the fix.", "After the outage, she stepped up and took full responsibility for the fix.", "After the outage, she stepped up and made full responsibility for the fix.", "After the outage, she stepped up and had full responsibility for the fix."], correct: 1, why: "“Take responsibility” fits the action of stepping up and accepting blame — “did/made/had responsibility” don't fit this sense." },
      { options: ["We gave an order for 200 units yesterday.", "We made an order for 200 units yesterday.", "We placed an order for 200 units yesterday.", "We did an order for 200 units yesterday."], correct: 2, why: "“Place an order” is the standard phrase for a purchase — “give an order” means issuing a command, and “make/do an order” aren't standard." },
      { options: ["The customer wants to give a complaint about the delayed delivery.", "The customer wants to do a complaint about the delayed delivery.", "The customer wants to take a complaint about the delayed delivery.", "The customer wants to file a complaint about the delayed delivery."], correct: 3, why: "“File a complaint” is the fixed collocation." },
      { options: ["Let's set a realistic deadline for this deliverable.", "Let's put a realistic deadline for this deliverable.", "Let's make a realistic deadline for this deliverable.", "Let's give a realistic deadline for this deliverable."], correct: 0, why: "“Set a deadline” is the fixed collocation — “put/make/give a deadline” aren't standard." },
      { options: ["What is your good name?", "What is your name?", "What is your name, please tell?", "Please tell me your good name."], correct: 1, why: "“What is your name?” is standard English — “good name” is an Indian-English-only addition with no equivalent in standard usage." },
      { options: ["I shifted to Bangalore two years back.", "I shifted to Bangalore since two years.", "I moved to Bangalore two years ago.", "I moved to Bangalore from two years."], correct: 2, why: "“Moved ... two years ago” is standard — “shifted” for relocating and “years back” / “since two years” are Indian-English patterns." },
      { options: ["My cousin brother is visiting us this weekend.", "My cousin sister is visiting us this weekend.", "My own cousin is visiting us this weekend.", "My cousin is visiting us this weekend."], correct: 3, why: "“Cousin” alone is standard English — “cousin brother” / “cousin sister” are Indian-English-specific redundant kinship terms." },
    ],
  },
  bands: [
    { max: 40, code: "Shaky", name: "Still guessing", desc: "“I am knowing” and “do a mistake” style slips still come naturally. Drill the core rule first: states (know, want, belong) never take the continuous, and fixed word-pairs (make/do/take + noun) have to be memorized one by one." },
    { max: 65, code: "Developing", name: "Getting there", desc: "Reliable on the obvious stative verbs and common collocations, but slips on the verbs that switch meaning (have, think) and the less common word pairs." },
    { max: 85, code: "Solid", name: "Reliable", desc: "Consistently correct across most items, with only occasional slips on the trickier dual-sense verbs or rarer collocations." },
    { max: 100, code: "Native-like", name: "Automatic", desc: "Handles the switch-meaning verbs (have, think) and the fixed word pairs without hesitation — and never says “good name” or “cousin brother.”" },
  ],
  ladder: [
    ["Shaky", "Still guessing"],
    ["Developing", "Getting there"],
    ["Solid", "Reliable"],
    ["Native-like", "Automatic"],
  ],
  ladderEnds: ["Shaky", "Native-like"],
  tiles: { labels: ["Stative verbs", "Collocations"] },
  footNote: "Each item has exactly one correct answer — check the review to see the rule behind it.",
};
