import type { DrillConfig } from "@/lib/tests/drill";

export const PREPOSITION_PARTY: DrillConfig = {
  id: "preposition-party",
  slug: "preposition-party",
  href: "/tests/preposition-party",
  accent: "steel",
  eyebrow: "Round 3 · Grammar drill",
  titleLead: "The ",
  titleEm: "Preposition",
  titleTail: " Party!",
  lede: 'A preposition is always followed by the -ing form — never "to do." Two parts: complete real corporate phrases from emails and meetings, then pick the right preposition in common collocations.',
  howto: [
    "<b>Part I — Fix the form.</b> Each sentence has a verb in brackets. Most blanks need just the -ing form — a few need the preposition too, so read the hint under each one.",
    "<b>Part II — Choose the preposition.</b> Pick the preposition that correctly leads into the gerund phrase.",
    "<b>Scoring:</b> each item is worth 1 point. Spelling is checked exactly, so read your answer back before submitting.",
  ],
  part1: {
    title: "Fix the form",
    note: "Type the -ing form of the verb in brackets.",
    fills: [
      {
        before: "I'm really looking forward to ",
        verb: "see",
        after: " you next week.",
        accept: ["seeing"],
        why: "“to” here belongs to “look forward to” — it's a preposition, not the infinitive marker, so it takes the -ing form.",
      },
      {
        before: "She strongly objects to ",
        verb: "change",
        after: " the schedule at the last minute.",
        accept: ["changing"],
        why: "“object to” — “to” is a preposition here too, so it takes a gerund.",
      },
      {
        before: "After years abroad, he finally got used to ",
        verb: "eat",
        after: " spicy food.",
        accept: ["eating"],
        why: "“get/be used to” means “accustomed to” — don't confuse it with “used to do” (a past habit), which takes the base verb.",
      },
      {
        before: "You can't finish the report without ",
        verb: "check",
        after: " the numbers twice.",
        accept: ["checking"],
        why: "“without” is a preposition.",
      },
      {
        before: "Before ",
        verb: "send",
        after: " the email, read it one more time.",
        accept: ["sending"],
        why: "“before” is a preposition here, so it takes the -ing form.",
      },
      {
        before: "Thank you so much ",
        verb: "take",
        after: " the time to walk us through the proposal.",
        accept: ["for taking"],
        why: "“Thank you for” + gerund — one of the most common phrases in professional emails.",
        hintExtra: "include the preposition",
      },
      {
        before: "We sincerely apologize ",
        verb: "cause",
        after: " any inconvenience this delay may have caused.",
        accept: ["for causing"],
        why: "“Apologize for” + gerund is the standard way to say sorry in a business email.",
        hintExtra: "include the preposition",
      },
      {
        before: "We remain fully committed ",
        verb: "deliver",
        after: " the project on schedule.",
        accept: ["to delivering"],
        why: "“Committed to” + gerund — “to” is a preposition here, not the infinitive marker, so it takes the -ing form.",
        hintExtra: "include the preposition",
      },
      {
        before: "Please proceed ",
        verb: "onboard",
        after: " the new vendor once legal has signed off.",
        accept: ["with onboarding"],
        why: "“Proceed with” + gerund is common in operational and project emails.",
        hintExtra: "include the preposition",
      },
      {
        before: "We're excited ",
        verb: "announce",
        after: " the launch of our new platform.",
        accept: ["about announcing", "to announce"],
        why: "“Excited about” + gerund works here — though “excited to announce” (with “to” as the infinitive marker, not a preposition) is just as common in real announcements.",
        hintExtra: "include the preposition",
      },
      {
        before: "Our support team is responsible ",
        verb: "maintain",
        after: " uptime across all regions.",
        accept: ["for maintaining"],
        why: "“Responsible for” + gerund — standard phrasing in role descriptions and SLAs.",
        hintExtra: "include the preposition",
      },
      {
        before: "Please refrain ",
        verb: "share",
        after: " this document outside the immediate team.",
        accept: ["from sharing"],
        why: "“Refrain from” + gerund is the standard phrase for a formal request not to do something.",
        hintExtra: "include the preposition",
      },
    ],
  },
  part2: {
    title: "Choose the preposition",
    note: "Pick the preposition that belongs before the gerund.",
    mcq: [
      { sentence: "She's incredibly good ___ solving last-minute problems.", options: ["at", "in", "for", "on"], correct: 0, why: "“good at” is the fixed adjective + preposition collocation." },
      { sentence: "He's always been afraid ___ public speaking.", options: ["from", "of", "about", "to"], correct: 1, why: "“afraid of” is the fixed collocation." },
      { sentence: "I'm not really interested ___ discussing politics at work.", options: ["at", "in", "on", "for"], correct: 1, why: "“interested in” is the fixed collocation." },
      { sentence: "They're capable ___ handling much bigger projects than this.", options: ["at", "for", "of", "with"], correct: 2, why: "“capable of” is the fixed collocation." },
      { sentence: "We're all excited ___ starting the new project next month.", options: ["for", "to", "about", "in"], correct: 2, why: "“excited about” is the fixed collocation." },
      { sentence: "He seemed tired ___ answering the same question over and over.", options: ["from", "with", "of", "about"], correct: 2, why: "“tired of” signals annoyance at something repeated; “tired from” would be physical exhaustion." },
      { sentence: "She's responsible ___ onboarding every new hire.", options: ["to", "of", "for", "with"], correct: 2, why: "“responsible for” is the fixed collocation." },
      { sentence: "He insisted ___ paying for dinner himself.", options: ["for", "on", "in", "about"], correct: 1, why: "“insist on” is the fixed collocation." },
      { sentence: "After months of trying, she finally succeeded ___ convincing the board.", options: ["at", "for", "in", "on"], correct: 2, why: "“succeed in” is the fixed collocation." },
      { sentence: "He apologized ___ being late to the client call.", options: ["about", "of", "for", "to"], correct: 2, why: "“apologize for” is the fixed collocation." },
      { sentence: "You can always rely ___ having his full support.", options: ["in", "on", "for", "at"], correct: 1, why: "“rely on” is the fixed collocation." },
      { sentence: "The committee approved ___ hiring two more engineers.", options: ["to", "for", "of", "on"], correct: 2, why: "“approve of” is the fixed collocation." },
      { sentence: "He strongly objects ___ changing the process this late.", options: ["on", "to", "for", "about"], correct: 1, why: "Same “to-as-preposition” trap as Part I — “object to”." },
      { sentence: "Let's focus ___ improving the onboarding flow first.", options: ["in", "at", "on", "to"], correct: 2, why: "“focus on” is the fixed collocation." },
      { sentence: "What was your reason ___ leaving the last job?", options: ["of", "for", "in", "to"], correct: 1, why: "“reason for” is the fixed collocation." },
      { sentence: "She's always shown a real interest ___ learning new languages.", options: ["for", "on", "in", "at"], correct: 2, why: "“interest in” is the fixed collocation." },
      { sentence: "What are our chances ___ winning this bid?", options: ["for", "of", "in", "with"], correct: 1, why: "“chance of” is the fixed collocation before a gerund." },
      { sentence: "They use a very hands-on method ___ teaching grammar.", options: ["in", "with", "of", "at"], correct: 2, why: "“method of” is the fixed collocation before a gerund." },
      { sentence: "He has a bad habit ___ checking his phone mid-meeting.", options: ["of", "for", "at", "to"], correct: 0, why: "“habit of” is the fixed collocation." },
      { sentence: "There's real difficulty ___ understanding the new policy.", options: ["of", "for", "at", "in"], correct: 3, why: "“difficulty in” is the standard form before a gerund." },
    ],
  },
  bands: [
    { max: 40, code: "Shaky", name: "Still guessing", desc: "Regularly picks the base verb or the wrong preposition. Drill the fixed-phrase list — look forward to, object to, get used to — before anything else." },
    { max: 65, code: "Developing", name: "Getting there", desc: "Reliable on the obvious triggers (after, before, without) but slips on fixed collocations and the “to” trap." },
    { max: 85, code: "Solid", name: "Reliable", desc: "Consistently correct on both common triggers and most collocations, with only occasional slips on rarer combinations." },
    { max: 100, code: "Native-like", name: "Automatic", desc: "Handles even the classic traps — look forward to, object to, used to vs. get used to — without hesitation." },
  ],
  ladder: [
    ["Shaky", "Still guessing"],
    ["Developing", "Getting there"],
    ["Solid", "Reliable"],
    ["Native-like", "Automatic"],
  ],
  ladderEnds: ["Shaky", "Native-like"],
  tiles: { kind: "part", labels: ["Form", "Prepositions"] },
  footNote:
    "Spelling is checked exactly (case-insensitive). A typo counts as wrong — check the review before arguing with your score.",
};
