import type { DrillConfig } from "@/lib/tests/drill";

export const TENSION_2: DrillConfig = {
  id: "tension-2",
  slug: "tension-2",
  href: "/tests/tension-2",
  accent: "rose",
  eyebrow: "Round 6 · Grammar drill, advanced",
  titleLead: "‘",
  titleEm: "Tense",
  titleTail: "’ion in the Air — Part 2",
  lede: "Four trickier patterns Part 1 didn't touch: duration before a past point, action in progress at a future moment, modal perfects (should have, must have, could have…), and the one rule that never takes \"will\" — time clauses.",
  howto: [
    "<b>Part I — Fix the tense.</b> Each sentence has a verb in brackets and context that pins down exactly one correct form. Type the full verb phrase.",
    "<b>Part II — Choose the right form.</b> Pick the form that fits the context from four options — several look alike, so read carefully.",
    "<b>Scoring:</b> each item is worth 1 point. A couple of Part I blanks accept more than one correct phrasing — spelling is still checked exactly.",
  ],
  part1: {
    title: "Fix the tense",
    note: "Type the correct tense of the verb in brackets — the context tells you which one.",
    fills: [
      { before: "She ", verb: "work", after: " on the proposal for three hours when the power went out.", accept: ["had been working"], why: "Duration leading up to a specific past point (“when the power went out”) takes the past perfect continuous.", group: "sequence" },
      { before: "By the time I joined the call, they ", verb: "discuss", after: " the budget for twenty minutes.", accept: ["had been discussing"], why: "Duration leading up to a past point (“by the time I joined”) takes the past perfect continuous.", group: "sequence" },
      { before: "This time next week, I ", verb: "present", after: " the results to the board.", accept: ["will be presenting"], why: "An action in progress at a specific future time point takes the future continuous.", group: "sequence" },
      { before: "Don't call at 9 — I ", verb: "drive", after: " to the airport then.", accept: ["will be driving"], why: "An action in progress at a specific future time (“at 9… then”) takes the future continuous.", group: "sequence" },
      { before: "I forgot to CC you — I ", verb: "include", after: " you from the start.", accept: ["should have included"], why: "Advice about a past action that didn't happen — “should have” + past participle.", group: "modal" },
      { before: "That email was harsh — I ", verb: "send", after: " it without reviewing first.", accept: ["shouldn't have sent"], why: "Criticism of a past action that did happen — “shouldn't have” + past participle.", group: "modal" },
      { before: "The dashboard is still down — someone ", verb: "restart", after: " the server without checking dependencies.", accept: ["must have restarted"], why: "A confident deduction about a past cause — “must have” + past participle.", group: "modal" },
      { before: "If we had known about the outage sooner, we ", verb: "warn", after: " the client in time.", accept: ["would have warned"], why: "Third conditional: the hypothetical result of an unreal past condition takes “would have” + past participle.", group: "modal" },
      { before: "You ", verb: "rush", after: " the deployment — the release window got extended, so it turned out fine.", accept: ["needn't have rushed"], why: "“Needn't have” + past participle means you did something that turned out to be unnecessary.", group: "modal" },
      { before: "Turns out there was a template for this all along — we ", verb: "save", after: " so much time if we'd known.", accept: ["could have saved", "would have saved"], why: "An unfulfilled possibility (or its hypothetical result) — “could have” or “would have” + past participle both work here.", group: "modal" },
      { before: "I'll let you know as soon as I ", verb: "hear", after: " back from legal.", accept: ["hear"], why: "After “as soon as” with future meaning, use the present simple — never “will hear”.", group: "sequence" },
      { before: "Please review the deck before you ", verb: "send", after: " it to the client.", accept: ["send"], why: "After “before” with future meaning, use the present simple — never “will send”.", group: "sequence" },
      { before: "We won't go live until QA ", verb: "sign", after: " off.", accept: ["signs"], why: "After “until” with future meaning, use the present simple — never “will sign”.", group: "sequence" },
    ],
  },
  part2: {
    title: "Choose the right form",
    note: "Pick the form that fits the context.",
    mcq: [
      { sentence: "He was exhausted because he ___ all day before the client meeting.", options: ["worked", "had worked", "had been working", "was working"], correct: 2, why: "Duration leading up to a past point, explaining a past state — past perfect continuous.", group: "sequence" },
      { sentence: "The team ___ overtime for weeks before management finally hired more staff.", options: ["worked", "had worked", "had been working", "were working"], correct: 2, why: "An extended, ongoing action before a past event takes the past perfect continuous.", group: "sequence" },
      { sentence: "I ___ the meeting this afternoon, so I can't join the call.", options: ["present", "will present", "will be presenting", "have presented"], correct: 2, why: "An action in progress at a specific future time takes the future continuous.", group: "sequence" },
      { sentence: "At 10 AM tomorrow, I ___ the client, so please don't schedule anything then.", options: ["meet", "will meet", "will be meeting", "have met"], correct: 2, why: "An action in progress at a specific future time, not a simple decision — future continuous.", group: "sequence" },
      { sentence: "The build only broke right after Priya's commit went in — she ___ a dependency version without realizing it.", options: ["must have changed", "should have changed", "would have changed", "might have changed"], correct: 0, why: "The timing pins the cause directly to her commit — strong evidence supports “must have” for confident deduction.", group: "modal" },
      { sentence: "We missed the flight because we left too late. We ___ earlier.", options: ["must have left", "should have left", "could have left", "might have left"], correct: 1, why: "Regret about a wiser action that didn't happen — “should have” for advice not taken.", group: "modal" },
      { sentence: "His badge never scanned at the gate today and he's not answering calls — he ___ home sick.", options: ["must have stayed", "might have stayed", "should have stayed", "would have stayed"], correct: 0, why: "Strong direct evidence (badge + unreachable) supports a confident deduction — “must have”.", group: "modal" },
      { sentence: "The cleaning crew's van is still in the lot — they ___ this floor yet.", options: ["can't have finished", "must have finished", "should have finished", "would have finished"], correct: 0, why: "Direct evidence (van still there) supports a confident negative deduction — “can't have”.", group: "modal" },
      { sentence: "We shipped a week early. If we'd waited for full QA, we ___ into more bugs.", options: ["would have run", "must have run", "should have run", "could have run"], correct: 0, why: "The hypothetical result of an unreal past condition — “would have” + past participle.", group: "modal" },
      { sentence: "That was too much detail for a client email — you ___ the internal numbers.", options: ["shouldn't have shared", "couldn't have shared", "might have shared", "would have shared"], correct: 0, why: "Criticism of something that happened but was unwise — “shouldn't have”.", group: "modal" },
      { sentence: "I'm not sure why the numbers don't match — someone ___ a typo in the formula.", options: ["must have made", "might have made", "should have made", "would have made"], correct: 1, why: "An uncertain guess about a past cause — “might have” (or “may have”), not the confident “must have”.", group: "modal" },
      { sentence: "Looking back, the rollout plan was about as good as it could get — we ___ it any differently, even with more time.", options: ["couldn't have done", "shouldn't have done", "wouldn't have done", "needn't have done"], correct: 0, why: "“Even with more time” rules out a better alternative being possible — “couldn't have” for “no better option existed”.", group: "modal" },
      { sentence: "Call me when you ___ at the office.", options: ["will arrive", "arrive", "are arriving", "have arrived"], correct: 1, why: "After “when” with future meaning, use the present simple.", group: "sequence" },
      { sentence: "I'll send the invite once the room ___ confirmed.", options: ["will be", "is", "will have been", "was"], correct: 1, why: "After “once” with future meaning, use the present simple.", group: "sequence" },
      { sentence: "As soon as the numbers ___ in, I'll forward them to you.", options: ["will come", "come", "are coming", "will have come"], correct: 1, why: "After “as soon as” with future meaning, use the present simple.", group: "sequence" },
      { sentence: "If the client ___ back today, put them straight through to me.", options: ["will call", "calls", "is calling", "will have called"], correct: 1, why: "After “if” (first conditional) with future meaning, use the present simple.", group: "sequence" },
      { sentence: "By the time the meeting ___, we'll have the numbers ready.", options: ["will start", "starts", "is starting", "will have started"], correct: 1, why: "After “by the time” with future meaning, use the present simple.", group: "sequence" },
      { sentence: "After you ___ the form, I'll process it right away.", options: ["will submit", "submit", "are submitting", "will have submitted"], correct: 1, why: "After “after” with future meaning, use the present simple.", group: "sequence" },
      { sentence: "I won't relax until this deal ___ closed.", options: ["will be", "is", "will have been", "was"], correct: 1, why: "After “until” with future meaning, use the present simple.", group: "sequence" },
    ],
  },
  bands: [
    { max: 40, code: "Tense", name: "Guessing under pressure", desc: "The advanced patterns — modal perfects, time clauses, the continuous forms — are still mostly a guess. Drill the no-will-in-time-clauses rule first; it's the most common daily error." },
    { max: 65, code: "Easing Up", name: "Getting the obvious ones", desc: "You catch the clearer cases but still mix up should have/must have/could have, or slip “will” into a when-clause." },
    { max: 85, code: "Steady", name: "Reliable under most conditions", desc: "Consistently correct across these harder patterns, with only occasional slips on the finer modal-perfect distinctions." },
    { max: 100, code: "Unshakeable", name: "Doesn't flinch", desc: "You handle every pattern here, including the modal-perfect nuances that trip up even fluent speakers." },
  ],
  ladder: [
    ["Tense", "Guessing under pressure"],
    ["Easing Up", "Getting the obvious ones"],
    ["Steady", "Reliable under most conditions"],
    ["Unshakeable", "Doesn't flinch"],
  ],
  ladderEnds: ["Tense", "Unshakeable"],
  tiles: {
    kind: "group",
    groups: ["modal", "sequence"],
    labels: ["Modal perfects", "Sequencing & timing"],
  },
  footNote:
    "Spelling is checked exactly (case-insensitive). A typo counts as wrong — check the review before arguing with your score.",
};
