import type { DrillConfig } from "@/lib/tests/drill";

export const TENSION: DrillConfig = {
  id: "tension",
  slug: "tension",
  href: "/tests/tension",
  accent: "rose",
  eyebrow: "Round 4 · Grammar drill",
  titleLead: "‘",
  titleEm: "Tense",
  titleTail: "’ion in the Air",
  lede: "Present perfect or simple past? Will or going to? The tense you pick changes what you're actually saying — and it shows in a work email. Two parts: fix the tense in real workplace sentences, then choose the right form in context.",
  howto: [
    "<b>Part I — Fix the tense.</b> Each sentence has a verb in brackets and a time cue (since, yesterday, by Friday…). Type the full correct verb form.",
    "<b>Part II — Choose the right form.</b> Pick the tense that fits the context from four options.",
    "<b>Scoring:</b> each item is worth 1 point. A few Part I blanks accept more than one correct phrasing — spelling is still checked exactly, so read your answer back before submitting.",
  ],
  part1: {
    title: "Fix the tense",
    note: "Type the correct tense of the verb in brackets — the time cue in the sentence tells you which one.",
    fills: [
      { before: "I ", verb: "work", after: " here for six years, so I know the systems well.", accept: ["have worked", "have been working"], why: "“For six years” up to now needs the present perfect (or present perfect continuous) — not the simple past.", group: "past" },
      { before: "We ", verb: "submit", after: " the proposal yesterday afternoon.", accept: ["submitted"], why: "“Yesterday afternoon” is a finished past time, so it takes the simple past, not the present perfect.", group: "past" },
      { before: "She ", verb: "send", after: " the invoice already, so you don't need to chase it.", accept: ["has sent", "sent"], why: "“Already” with no specific past time signals the present perfect — “has sent” is the textbook form, though “sent” is common in informal speech.", group: "past" },
      { before: "Nobody ", verb: "respond", after: " to my email since Friday.", accept: ["has responded"], why: "“Since Friday” marks a starting point continuing to now — present perfect.", group: "past" },
      { before: "By the way, we ", verb: "finalize", after: " the vendor contract last week.", accept: ["finalized"], why: "“Last week” is a specific finished time, so it takes the simple past.", group: "past" },
      { before: "She ", verb: "lead", after: " this account since March, and client satisfaction has never been higher.", accept: ["has been leading", "has led"], why: "An action continuing up to now, with emphasis on duration, takes the present perfect continuous.", group: "past" },
      { before: "They ", verb: "negotiate", after: " with the supplier for three weeks now, with no resolution yet.", accept: ["have been negotiating", "have negotiated"], why: "“For three weeks now” with an ongoing, unfinished action needs the present perfect continuous.", group: "past" },
      { before: "By the time the client called, we ", verb: "resolve", after: " the issue and closed the ticket.", accept: ["had resolved"], why: "“By the time” + a past event needs the past perfect for whatever happened earlier — “closed the ticket” confirms it was already done.", group: "past" },
      { before: "The meeting ", verb: "start", after: " before I managed to join the call.", accept: ["had started"], why: "The starting happened before the joining — the earlier of two past events takes the past perfect.", group: "past" },
      { before: "I ", verb: "meet", after: " the client at 3 PM tomorrow — it's already on my calendar.", accept: ["am meeting"], why: "A fixed, pre-arranged plan is expressed with the present continuous, not “will”.", group: "future" },
      { before: "By Friday, I ", verb: "finish", after: " the first draft of the report.", accept: ["will have finished", "will finish"], why: "A task completed by a specific future deadline is most precisely expressed with the future perfect, though plain “will” is common too.", group: "future" },
      { before: "Careful with that server — it ", verb: "crash", after: " if we push this update now.", accept: ["is going to crash"], why: "A prediction based on something you can see right now uses “going to”, not “will”.", group: "future" },
      { before: "My manager said she ", verb: "review", after: " the proposal by Monday.", accept: ["would review"], why: "“Will” shifts back to “would” when you report what someone said.", group: "future" },
    ],
  },
  part2: {
    title: "Choose the right form",
    note: "Pick the verb form that fits the context.",
    mcq: [
      { sentence: "I ___ three emails about this already, and it's not even noon.", options: ["wrote", "have written", "was writing", "had written"], correct: 1, why: "“Already” + an explicitly unfinished period (“not even noon”) signals the present perfect.", group: "past" },
      { sentence: "We ___ the client last Tuesday to confirm the schedule.", options: ["have called", "call", "called", "were calling"], correct: 2, why: "“Last Tuesday” is a specific finished past time, so the simple past is correct.", group: "past" },
      { sentence: "He ___ in this role since 2020.", options: ["worked", "has worked", "was working", "works"], correct: 1, why: "“Since 2020” marks a starting point continuing to now — present perfect.", group: "past" },
      { sentence: "___ a client presentation before?", options: ["Did you ever give", "Have you ever given", "Were you ever giving", "Had you ever given"], correct: 1, why: "“Ever…before” asking about life experience up to now takes the present perfect.", group: "past" },
      { sentence: "The team ___ the deadline twice this quarter, and we still have six weeks left.", options: ["missed", "has missed", "was missing", "had missed"], correct: 1, why: "“This quarter” is still an unfinished time period, so the present perfect is correct.", group: "past" },
      { sentence: "I ___ this report all morning, and I'm still not done — I need a break.", options: ["wrote", "have written", "have been writing", "was writing"], correct: 2, why: "Emphasis on the ongoing, unfinished activity and its duration takes the present perfect continuous.", group: "past" },
      { sentence: "Sales ___ steadily since the new campaign launched.", options: ["have been rising", "rose", "had risen", "rise"], correct: 0, why: "A trend continuing up to now takes the present perfect continuous.", group: "past" },
      { sentence: "You look exhausted — ___ overtime again?", options: ["did you work", "have you worked", "have you been working", "were you working"], correct: 2, why: "Asking about a recent, ongoing activity with a visible present result takes the present perfect continuous.", group: "past" },
      { sentence: "When I checked my inbox, she ___ the files already.", options: ["sent", "has sent", "had sent", "was sending"], correct: 2, why: "Her sending happened before your checking — the earlier of two past events takes the past perfect.", group: "past" },
      { sentence: "The plane ___ by the time we reached the airport.", options: ["left", "has left", "had left", "was leaving"], correct: 2, why: "“By the time” + a past event needs the past perfect for whatever happened first.", group: "past" },
      { sentence: "I realized I ___ my badge at home.", options: ["forgot", "have forgotten", "had forgotten", "was forgetting"], correct: 2, why: "The forgetting happened before the realizing — past perfect for the earlier event.", group: "past" },
      { sentence: "Look at those clouds — it ___ any minute.", options: ["will rain", "is going to rain", "rains", "has rained"], correct: 1, why: "A prediction based on present evidence uses “going to”, not “will”.", group: "future" },
      { sentence: "The train ___ at 6 PM — check the schedule.", options: ["leaves", "will leave", "is going to leave", "has left"], correct: 0, why: "Timetables and fixed schedules use the present simple, not “will”.", group: "future" },
      { sentence: "By next year, the company ___ its headquarters twice.", options: ["will move", "will have moved", "is moving", "moved"], correct: 1, why: "An action completed by a specific future point takes the future perfect.", group: "future" },
      { sentence: "I think I ___ you a call later today to go over the numbers.", options: ["give", "am going to give", "will give", "have given"], correct: 2, why: "A decision made at the moment of speaking (“I think I…”) uses “will”, not “going to”.", group: "future" },
      { sentence: "She said she ___ help me the next day.", options: ["can help", "could help", "will help", "would help"], correct: 1, why: "“Can” shifts back to “could” in reported speech.", group: "future" },
      { sentence: "He mentioned they ___ the budget.", options: ["review", "are reviewing", "were reviewing", "had reviewed"], correct: 2, why: "Present continuous shifts back to past continuous in reported speech.", group: "future" },
      { sentence: "She told me she ___ the audit.", options: ["finished", "has finished", "had finished", "was finishing"], correct: 2, why: "Present perfect shifts back to past perfect in reported speech.", group: "future" },
      { sentence: "He said the client ___ the next day.", options: ["will sign", "would sign", "signs", "had signed"], correct: 1, why: "“Will” shifts back to “would” in reported speech.", group: "future" },
    ],
  },
  bands: [
    { max: 40, code: "Tense", name: "Guessing under pressure", desc: "Simple past and present perfect blur together, and the future forms (will vs. going to) are mostly a coin flip. Drill the since/for + specific-past-time rule first — it fixes the most errors fastest." },
    { max: 65, code: "Easing Up", name: "Getting the obvious ones", desc: "You catch the clear cases but still slip on sequencing two past events, reported speech, and the less common future forms." },
    { max: 85, code: "Steady", name: "Reliable under most conditions", desc: "Consistently correct across tenses, with only occasional slips on the trickier reported-speech and future-perfect patterns." },
    { max: 100, code: "Unshakeable", name: "Doesn't flinch", desc: "You handle every tense trap here, including the ones — reported speech, future perfect, present perfect continuous — that catch even fluent speakers off guard." },
  ],
  ladder: [
    ["Tense", "Guessing under pressure"],
    ["Easing Up", "Getting the obvious ones"],
    ["Steady", "Reliable under most conditions"],
    ["Unshakeable", "Doesn't flinch"],
  ],
  ladderEnds: ["Tense", "Unshakeable"],
  tiles: {
    kind: "group",
    groups: ["past", "future"],
    labels: ["Past tenses", "Future & reported speech"],
  },
  footNote:
    "A few answers accept more than one correct phrasing (e.g. “has led” or “has been leading”). Spelling is still checked exactly — check the review before arguing with your score.",
};
