/**
 * Word-of-the-day vocabulary bank for the landing page card. 200 entries,
 * built up in five reviewed calibration batches (see conversation history)
 * before generating the remaining bulk in that same style. Workplace-
 * relevant, moderate difficulty (similar register to the Shrink It! test's
 * vocabulary), and no duplicates with words already used as test content
 * elsewhere.
 */
export type WordSentiment = "positive" | "negative" | "neutral";

export type WordEntry = {
  word: string;
  partOfSpeech: string;
  sentiment: WordSentiment;
  meaning: string;
  example: string;
};

export const WORDS: WordEntry[] = [
  // --- Calibration batches (reviewed) ---
  {
    word: "Pragmatic",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Dealing with things sensibly and realistically, based on what actually works rather than on theory or ideals.",
    example: "Rather than debating the perfect solution for hours, the team took a pragmatic approach and shipped a fix that worked.",
  },
  {
    word: "Candid",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Truthful and straightforward, even when the truth might be uncomfortable to hear.",
    example: "In her candid feedback, the manager admitted the launch timeline had been too optimistic.",
  },
  {
    word: "Diligent",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Showing careful and persistent effort in one's work or duties.",
    example: "His diligent tracking of every bug meant nothing slipped through before release.",
  },
  {
    word: "Versatile",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Able to adapt to many different functions, roles, or situations.",
    example: "The new hire turned out to be versatile, moving easily between design work and customer calls.",
  },
  {
    word: "Conundrum",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "A confusing and difficult problem or question with no easy answer.",
    example: "Choosing between the two vendors was a conundrum, since each one solved a different half of the problem.",
  },
  {
    word: "Discrepancy",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "A lack of compatibility or similarity between two or more facts.",
    example: "Finance flagged a discrepancy between the invoice total and the purchase order.",
  },
  {
    word: "Tenacious",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Tending to keep a firm hold of something; persistent in pursuing a goal.",
    example: "Her tenacious follow-up finally got the vendor to fix the recurring outage.",
  },
  {
    word: "Prudent",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Acting with, or showing, care and forethought, especially about risk.",
    example: "It seemed prudent to test the rollback plan before touching the production database.",
  },
  {
    word: "Skeptical",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Not easily convinced; having doubts about a claim.",
    example: "The board stayed skeptical of the forecast until the numbers were independently verified.",
  },
  {
    word: "Leverage",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To use something to maximum advantage.",
    example: "The team decided to leverage the existing API instead of building a new one from scratch.",
  },
  {
    word: "Streamline",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To make a process or system more efficient by simplifying it.",
    example: "The new form was designed to streamline the approval process for expense claims.",
  },
  {
    word: "Reluctant",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Unwilling and hesitant to do something.",
    example: "He was reluctant to sign off on the design until the accessibility review was complete.",
  },
  {
    word: "Discern",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To perceive or recognize something, often with some difficulty.",
    example: "It took a second read to discern which requirement was actually a hard constraint.",
  },
  {
    word: "Precedent",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "An earlier event or decision treated as an example to be followed in similar cases.",
    example: "Approving this exception could set a precedent that other teams would expect too.",
  },
  {
    word: "Ascertain",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To find out for certain; to make sure of something.",
    example: "Before promising a launch date, she wanted to ascertain that the vendor could actually deliver on time.",
  },
  {
    word: "Discretion",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "The freedom to decide what should be done in a particular situation.",
    example: "The manager used her discretion to approve the refund without escalating it.",
  },
  {
    word: "Reconcile",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To make two things compatible, or to settle a disagreement between them.",
    example: "It took an extra day to reconcile the two spreadsheets before the numbers matched.",
  },
  {
    word: "Plausible",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Seeming reasonable or probable, though not necessarily verified.",
    example: "The team offered a plausible explanation for the delay, but nobody double-checked it.",
  },
  {
    word: "Nuance",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A subtle difference in meaning, expression, or opinion.",
    example: "A lot of the disagreement came down to a nuance in how \"urgent\" was defined.",
  },
  {
    word: "Arbitrary",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Based on random choice or personal whim rather than reason.",
    example: "Picking Friday as the deadline felt arbitrary since no one checked the team's other commitments.",
  },
  {
    word: "Circumvent",
    partOfSpeech: "verb",
    sentiment: "negative",
    meaning: "To find a way around an obstacle or rule.",
    example: "Instead of raising the blocker, he tried to circumvent the approval process entirely.",
  },
  {
    word: "Robust",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Strong and unlikely to fail or break under pressure.",
    example: "The new pipeline was far more robust, surviving three outages without dropping a single job.",
  },

  // --- Remaining bank, generated in the same style ---
  {
    word: "Astute",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Having or showing an ability to accurately assess situations and turn this to one's advantage.",
    example: "Her astute read of the client's hesitation let her adjust the pitch before losing the deal.",
  },
  {
    word: "Resilient",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Able to recover quickly from difficulties.",
    example: "The team stayed resilient through three failed deployments before finally getting the release out.",
  },
  {
    word: "Cohesive",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Forming a unified whole; working well together.",
    example: "The redesign made the app feel far more cohesive across every screen.",
  },
  {
    word: "Viable",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Capable of working successfully; feasible.",
    example: "Only one of the three proposals turned out to be financially viable.",
  },
  {
    word: "Comprehensive",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Complete and including everything that is necessary.",
    example: "The onboarding guide is comprehensive enough that new hires rarely need to ask questions.",
  },
  {
    word: "Rigorous",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Extremely thorough and careful.",
    example: "The security team ran a rigorous review before approving the new vendor.",
  },
  {
    word: "Adept",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Very skilled or proficient at something.",
    example: "She's adept at turning messy requirements into a clear spec.",
  },
  {
    word: "Prevalent",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Widespread in a particular area or at a particular time.",
    example: "Remote work is far more prevalent now than it was five years ago.",
  },
  {
    word: "Volatile",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Liable to change rapidly and unpredictably.",
    example: "The market was too volatile for the team to commit to a fixed-price contract.",
  },
  {
    word: "Judicious",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Having, showing, or done with good judgment or sense.",
    example: "A judicious use of the remaining budget kept the project from running over.",
  },
  {
    word: "Sporadic",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Occurring at irregular intervals; scattered.",
    example: "The outages were sporadic enough that the root cause took weeks to pin down.",
  },
  {
    word: "Explicit",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Stated clearly and in detail, leaving no room for confusion.",
    example: "The contract was explicit about who owned the intellectual property.",
  },
  {
    word: "Implicit",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Implied though not directly expressed.",
    example: "There was an implicit expectation that everyone would be online for the launch.",
  },
  {
    word: "Cordial",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Warm and friendly, though often somewhat formal.",
    example: "The two competing teams kept things cordial despite disagreeing on the approach.",
  },
  {
    word: "Amicable",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Characterized by friendliness and an absence of discord.",
    example: "They reached an amicable agreement on how to split the shared codebase.",
  },
  {
    word: "Indispensable",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Absolutely necessary; too important to be without.",
    example: "The on-call runbook became indispensable during the migration weekend.",
  },
  {
    word: "Superfluous",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Unnecessary, especially through being more than what is needed.",
    example: "Half the fields on the form were superfluous and just slowed people down.",
  },
  {
    word: "Vigilant",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Keeping careful watch for possible danger or problems.",
    example: "The ops team stayed vigilant through the entire holiday traffic spike.",
  },
  {
    word: "Coherent",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Logical and consistent; easy to follow.",
    example: "The final proposal was far more coherent once the two drafts were merged.",
  },
  {
    word: "Elusive",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Difficult to find, catch, or achieve.",
    example: "A root cause for the intermittent crash remained elusive for over a week.",
  },
  {
    word: "Tangible",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Perceptible by touch, or clear and definite.",
    example: "The redesign delivered a tangible drop in support tickets within a month.",
  },
  {
    word: "Intangible",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Unable to be touched or precisely defined; abstract.",
    example: "Team morale is intangible, but it showed up clearly in the retention numbers.",
  },
  {
    word: "Deliberate",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Done consciously and intentionally.",
    example: "The delay was deliberate, giving QA an extra day before the release.",
  },
  {
    word: "Impartial",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Treating all sides equally; not biased.",
    example: "An impartial reviewer was brought in to settle the disagreement over the design.",
  },
  {
    word: "Credible",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Able to be believed; convincing.",
    example: "The postmortem needed a credible explanation before leadership would sign off on the fix.",
  },
  {
    word: "Innate",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Existing from birth; inborn rather than learned.",
    example: "He had an innate sense for which bugs were actually urgent.",
  },
  {
    word: "Proactive",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Acting in advance to deal with an expected difficulty.",
    example: "Being proactive about backups saved the team when the server failed.",
  },
  {
    word: "Reactive",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Acting in response to a problem rather than anticipating it.",
    example: "The support team had become purely reactive, only fixing things after customers complained.",
  },
  {
    word: "Punctual",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Happening or arriving exactly at the time arranged.",
    example: "She was punctual for every stand-up, even the ones scheduled too early.",
  },
  {
    word: "Conscientious",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Wishing to do what is right, especially to do one's work well.",
    example: "His conscientious note-taking meant the handover documentation was actually usable.",
  },
  {
    word: "Frugal",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Sparing or economical with money or resources.",
    example: "The startup stayed frugal, renting servers only when traffic actually justified it.",
  },
  {
    word: "Lucrative",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Producing a great deal of profit.",
    example: "The enterprise contract turned out to be far more lucrative than the smaller deals combined.",
  },
  {
    word: "Precarious",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Not securely held or in position; likely to fail.",
    example: "The whole release plan felt precarious once the lead engineer went on leave.",
  },
  {
    word: "Stringent",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Strict, precise, and exacting.",
    example: "The new compliance rules were stringent enough to require a full audit of the codebase.",
  },
  {
    word: "Lenient",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "More merciful or tolerant than expected.",
    example: "The manager was lenient about the missed deadline given the unexpected outage.",
  },
  {
    word: "Inevitable",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Certain to happen; unavoidable.",
    example: "A rewrite of the legacy module became inevitable once the third workaround failed.",
  },
  {
    word: "Formidable",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Inspiring fear or respect through being impressively powerful or capable.",
    example: "The competitor's engineering team was a formidable presence in every industry benchmark.",
  },
  {
    word: "Congruent",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "In agreement or harmony; matching.",
    example: "The new pricing model was finally congruent with what sales had been promising.",
  },
  {
    word: "Discordant",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Disagreeing or incongruous; clashing.",
    example: "The two departments kept sending discordant updates to the same customer.",
  },
  {
    word: "Ephemeral",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Lasting for a very short time.",
    example: "The traffic spike was ephemeral, gone within an hour of the campaign ending.",
  },
  {
    word: "Perennial",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Lasting or existing for a long or apparently infinite time; recurring.",
    example: "Slow onboarding has been a perennial complaint in every employee survey.",
  },
  {
    word: "Exhaustive",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Fully comprehensive; including all elements or aspects.",
    example: "An exhaustive review of the logs finally revealed the timing bug.",
  },
  {
    word: "Anomalous",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Deviating from what is standard, normal, or expected.",
    example: "One anomalous spike in memory usage turned out to point at the real leak.",
  },
  {
    word: "Unequivocal",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Leaving no doubt; unambiguous.",
    example: "Leadership gave an unequivocal yes to extending the deadline by a week.",
  },
  {
    word: "Provisional",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Arranged or existing for the present, possibly to be changed later.",
    example: "A provisional fix went out while the team worked on a permanent solution.",
  },
  {
    word: "Nominal",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Existing in name only; a token amount.",
    example: "The fee for internal tools was nominal, mostly to discourage unused sign-ups.",
  },
  {
    word: "Substantive",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Having a firm basis in reality; important or meaningful.",
    example: "The two teams finally had a substantive conversation about who owned the API.",
  },
  {
    word: "Novel",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "New or unusual in an interesting way.",
    example: "Her novel approach to caching cut the page load time in half.",
  },
  {
    word: "Obsolete",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "No longer produced or used; outdated.",
    example: "The old ticketing system was declared obsolete once the new one went live.",
  },
  {
    word: "Scalable",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Able to be changed in size or scale to meet demand.",
    example: "The architecture needed to be scalable enough to handle ten times the current traffic.",
  },
  {
    word: "Sustainable",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Able to be maintained at a certain rate or level over time.",
    example: "Working weekends to hit the deadline wasn't a sustainable pace for the team.",
  },
  {
    word: "Ambivalent",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Having mixed feelings or contradictory ideas about something.",
    example: "She felt ambivalent about the promotion, excited but wary of the extra travel.",
  },
  {
    word: "Wary",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Feeling or showing caution about possible dangers or problems.",
    example: "He stayed wary of the vendor's promises after the last missed deadline.",
  },
  {
    word: "Circumspect",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Wary and unwilling to take risks; cautious.",
    example: "Legal advised a circumspect approach before announcing the partnership publicly.",
  },
  {
    word: "Forthright",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Direct and outspoken.",
    example: "Her forthright feedback in the review made the next draft much stronger.",
  },
  {
    word: "Diplomatic",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Having or showing skill in dealing with people sensitively.",
    example: "He was diplomatic about the missed deadline, focusing on next steps instead of blame.",
  },
  {
    word: "Tactful",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Having or showing sensitivity in dealing with others or with difficult issues.",
    example: "She found a tactful way to tell the client the estimate had doubled.",
  },
  {
    word: "Blunt",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Uncompromisingly forthright, without regard for the other person's feelings.",
    example: "His blunt review of the proposal caught the junior designer off guard.",
  },
  {
    word: "Terse",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Sparing in the use of words; abrupt.",
    example: "The incident report was so terse that nobody could tell what had actually broken.",
  },
  {
    word: "Verbose",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Using more words than needed; wordy.",
    example: "The original spec was so verbose that half the team skipped reading it.",
  },
  {
    word: "Lucid",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Expressed clearly; easy to understand.",
    example: "His lucid explanation of the outage finally made sense to the non-technical stakeholders.",
  },
  {
    word: "Cryptic",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Mysterious or obscure in meaning.",
    example: "The commit message was so cryptic that nobody remembered why the change was made.",
  },
  {
    word: "Nebulous",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Unclear, vague, or ill-defined.",
    example: "The project brief was nebulous enough that three teams interpreted it three different ways.",
  },
  {
    word: "Palpable",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Able to be touched or felt; so intense as to seem almost tangible.",
    example: "There was a palpable sense of relief once the migration finished without incident.",
  },
  {
    word: "Rampant",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Flourishing or spreading unchecked.",
    example: "Rumors about layoffs were rampant before the official announcement went out.",
  },
  {
    word: "Chronic",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Persisting for a long time or constantly recurring.",
    example: "The chronic understaffing on support finally caught leadership's attention.",
  },
  {
    word: "Acute",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Present or experienced to a severe degree; sharp.",
    example: "The acute shortage of reviewers slowed every pull request that week.",
  },
  {
    word: "Transient",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Lasting only for a short time; temporary.",
    example: "The error was transient, appearing only under a very specific network condition.",
  },
  {
    word: "Static",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Lacking movement, action, or change.",
    example: "The dashboard stayed static for hours because the data pipeline had silently failed.",
  },
  {
    word: "Dynamic",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Characterized by constant change or activity.",
    example: "The pricing page needed to be dynamic, updating instantly as inventory changed.",
  },
  {
    word: "Pertinent",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Relevant or applicable to a particular matter.",
    example: "Only the pertinent logs were shared with the vendor to speed up the investigation.",
  },
  {
    word: "Extraneous",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Irrelevant or unrelated to the subject being dealt with.",
    example: "Cutting the extraneous slides made the deck twice as effective.",
  },
  {
    word: "Marginal",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "So small or slight as to be near the limit; minimal.",
    example: "The new algorithm gave only a marginal improvement over the old one.",
  },
  {
    word: "Optimal",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Best or most favorable under the circumstances.",
    example: "Running the batch job overnight was the optimal time given the server load.",
  },
  {
    word: "Suboptimal",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Below the best possible standard or level.",
    example: "The workaround was suboptimal but kept customers unblocked until the real fix shipped.",
  },
  {
    word: "Adverse",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Preventing success or development; harmful.",
    example: "The new policy had an adverse effect on how quickly tickets got resolved.",
  },
  {
    word: "Favorable",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Advantageous; encouraging or approving.",
    example: "Early feedback on the beta was favorable enough to move up the launch.",
  },
  {
    word: "Detrimental",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Tending to cause harm.",
    example: "Skipping code review turned out to be detrimental to the overall quality of the release.",
  },
  {
    word: "Beneficial",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Resulting in good; favorable or advantageous.",
    example: "The extra week of testing proved beneficial once two major bugs turned up.",
  },
  {
    word: "Consequential",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Following as a result or effect; significant.",
    example: "That one architecture decision turned out to be far more consequential than anyone expected.",
  },
  {
    word: "Trivial",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Of little value or importance.",
    example: "What seemed like a trivial config change ended up causing the entire outage.",
  },
  {
    word: "Paramount",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "More important than anything else; supreme.",
    example: "Data privacy was paramount when the new feature was being designed.",
  },
  {
    word: "Salient",
    partOfSpeech: "adjective",
    sentiment: "neutral",
    meaning: "Most noticeable or important.",
    example: "The most salient point in the report was buried on the last page.",
  },
  {
    word: "Cursory",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Hasty and therefore not thorough or detailed.",
    example: "A cursory glance at the logs missed the pattern that a closer look revealed.",
  },
  {
    word: "Thorough",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Complete with regard to every detail; not superficial.",
    example: "A thorough audit of the permissions turned up several accounts that should've been revoked.",
  },
  {
    word: "Discerning",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Having or showing good judgment, especially about aesthetic or intellectual matters.",
    example: "A discerning eye caught the inconsistency in the design system before it shipped.",
  },
  {
    word: "Perceptive",
    partOfSpeech: "adjective",
    sentiment: "positive",
    meaning: "Having or showing sensitive insight; quick to notice things.",
    example: "Her perceptive question during the demo exposed a gap nobody had considered.",
  },
  {
    word: "Oblivious",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Not aware of or not concerned about what is happening.",
    example: "He was oblivious to the fact that the whole channel had been discussing the outage.",
  },
  {
    word: "Complacent",
    partOfSpeech: "adjective",
    sentiment: "negative",
    meaning: "Showing smug or uncritical satisfaction with oneself.",
    example: "After a string of smooth releases, the team had grown a little complacent about testing.",
  },
  {
    word: "Consensus",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "General agreement among a group.",
    example: "It took two meetings to reach consensus on which framework to use.",
  },
  {
    word: "Dissent",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "The holding or expression of opinions at variance with those commonly held.",
    example: "One engineer's dissent during planning turned out to be exactly right.",
  },
  {
    word: "Rapport",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "A close and harmonious relationship.",
    example: "The account manager built enough rapport with the client to renegotiate the timeline.",
  },
  {
    word: "Momentum",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "The strength or force gained by movement or a series of events.",
    example: "The team lost momentum after the third scope change in a month.",
  },
  {
    word: "Attrition",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "The gradual reduction of a workforce through resignations or retirements.",
    example: "Attrition on the support team meant every remaining agent handled twice the tickets.",
  },
  {
    word: "Turnover",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "The rate at which employees leave a workforce and are replaced.",
    example: "High turnover in the department made it hard to keep any process consistent.",
  },
  {
    word: "Overhead",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "The ongoing operating costs of running a business or process.",
    example: "Maintaining the old servers added more overhead than migrating to the cloud would.",
  },
  {
    word: "Bottleneck",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "A point of congestion that slows down a process.",
    example: "Code review had become the biggest bottleneck in the release pipeline.",
  },
  {
    word: "Milestone",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "A significant point or event in a project's development.",
    example: "Hitting the beta milestone two weeks early gave the team some breathing room.",
  },
  {
    word: "Benchmark",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A standard against which things can be measured or judged.",
    example: "The new server config was tested against last quarter's performance benchmark.",
  },
  {
    word: "Metric",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A measurement used to track and assess a process.",
    example: "Response time became the team's main metric for support quality.",
  },
  {
    word: "Anomaly",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "Something that deviates from what is standard or expected.",
    example: "An anomaly in the billing data triggered a full reconciliation.",
  },
  {
    word: "Deviation",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A departure from an established course or standard.",
    example: "Any deviation from the style guide now gets flagged automatically in review.",
  },
  {
    word: "Threshold",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A level or point at which something begins or changes.",
    example: "Once error rates crossed the alert threshold, the on-call engineer was paged.",
  },
  {
    word: "Latitude",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "Freedom from restriction in action or judgment.",
    example: "Senior engineers were given more latitude to choose their own tools.",
  },
  {
    word: "Mandate",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "An official order or commission to do something.",
    example: "The new mandate required every service to pass a security scan before deployment.",
  },
  {
    word: "Directive",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "An official or authoritative instruction.",
    example: "Leadership issued a directive freezing new hires until the budget review was complete.",
  },
  {
    word: "Initiative",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "The ability to assess and initiate things independently, or a new plan or process.",
    example: "The cost-cutting initiative ended up saving more than expected in its first quarter.",
  },
  {
    word: "Incentive",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "A thing that motivates or encourages someone to do something.",
    example: "The referral bonus was a strong incentive for employees to spread the word.",
  },
  {
    word: "Deterrent",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A thing that discourages or is intended to discourage someone from doing something.",
    example: "Mandatory code review acted as a deterrent against rushed, untested changes.",
  },
  {
    word: "Liability",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "A thing for which someone is responsible, especially a debt or obligation.",
    example: "The unpatched server was flagged as a liability during the security audit.",
  },
  {
    word: "Asset",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "A useful or valuable thing, person, or quality.",
    example: "Her experience with the legacy system became a huge asset during the migration.",
  },
  {
    word: "Deficit",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "The amount by which something, especially a sum of money, is too small.",
    example: "The project ran at a time deficit almost from the very first sprint.",
  },
  {
    word: "Surplus",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "An amount left over when requirements have been met.",
    example: "The extra budget surplus was redirected toward tooling improvements.",
  },
  {
    word: "Compromise",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "An agreement reached by each side making concessions.",
    example: "They reached a compromise on the API design that neither team loved but both could live with.",
  },
  {
    word: "Stalemate",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "A situation in which no progress can be made; a deadlock.",
    example: "The naming debate hit a stalemate until a third option was proposed.",
  },
  {
    word: "Impasse",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "A situation in which no progress is possible; a deadlock.",
    example: "Negotiations over the contract terms reached an impasse by Friday afternoon.",
  },
  {
    word: "Rationale",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A set of reasons or a logical basis for a course of action.",
    example: "The rationale behind the redesign wasn't clear until the usability data came in.",
  },
  {
    word: "Premise",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A previous statement from which another is inferred; a basic assumption.",
    example: "The whole roadmap was built on the premise that mobile traffic would keep growing.",
  },
  {
    word: "Inference",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A conclusion reached on the basis of evidence and reasoning.",
    example: "The support team's inference about the cause turned out to be exactly right.",
  },
  {
    word: "Assumption",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A thing that is accepted as true without proof.",
    example: "The estimate was based on an assumption that the API wouldn't change mid-project.",
  },
  {
    word: "Hypothesis",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A proposed explanation made on the basis of limited evidence.",
    example: "Their hypothesis was that caching, not the database, was causing the slowdown.",
  },
  {
    word: "Anecdote",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A short account of a particular incident, often used to illustrate a point.",
    example: "One customer's anecdote about a confusing checkout flow led to a full redesign.",
  },
  {
    word: "Testimony",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A formal statement or evidence given in support of a fact.",
    example: "User testimony during the interviews confirmed what the analytics had already suggested.",
  },
  {
    word: "Disclosure",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "The action of making new or secret information known.",
    example: "Full disclosure of the outage timeline was shared with affected customers.",
  },
  {
    word: "Confidentiality",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "The state of keeping something private or secret.",
    example: "Confidentiality clauses prevented either company from discussing the deal terms publicly.",
  },
  {
    word: "Transparency",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "The quality of being open and honest; easy to see through.",
    example: "Weekly status updates were introduced to improve transparency across teams.",
  },
  {
    word: "Accountability",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "The fact of being responsible for one's actions and answerable for them.",
    example: "Clear ownership brought a new level of accountability to the on-call rotation.",
  },
  {
    word: "Autonomy",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "The right or condition of self-government; independence.",
    example: "Giving teams more autonomy over their own tooling sped up decision-making.",
  },
  {
    word: "Hierarchy",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A system in which people or things are ranked according to status.",
    example: "Flattening the hierarchy meant engineers could talk directly to the product lead.",
  },
  {
    word: "Delegation",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "The assignment of responsibility or authority to another person.",
    example: "Better delegation freed up the manager to focus on the roadmap.",
  },
  {
    word: "Escalation",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "The action of a situation becoming more serious or intense.",
    example: "The ticket needed escalation once the customer's account was completely locked out.",
  },
  {
    word: "Feasibility",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "The state of being easily or conveniently done.",
    example: "A quick feasibility study ruled out the more ambitious redesign for this quarter.",
  },
  {
    word: "Viability",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "The ability to work successfully; feasibility.",
    example: "The pilot program proved the viability of the new onboarding flow.",
  },
  {
    word: "Scrutiny",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "Critical observation or examination.",
    example: "The vendor contract came under scrutiny after the second missed deadline.",
  },
  {
    word: "Oversight",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "Watchful and responsible care; also, an unintentional failure to notice something.",
    example: "Better oversight of the deployment process caught the misconfigured server before launch.",
  },
  {
    word: "Compliance",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "The action of conforming to a rule, such as a policy or standard.",
    example: "Compliance with the new data policy required updating every legacy form.",
  },
  {
    word: "Repercussion",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "An unintended consequence of an action, often negative.",
    example: "Skipping the migration test had a repercussion nobody had planned for.",
  },
  {
    word: "Ramification",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "A consequence of an action, especially one that is complex or unwelcome.",
    example: "The pricing change had ramifications for three other teams' roadmaps.",
  },
  {
    word: "Implication",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A conclusion that can be drawn though not explicitly stated; a likely consequence.",
    example: "The implication of the delay was that the whole quarter's plan needed revisiting.",
  },
  {
    word: "Prerequisite",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A thing required as a prior condition for something else to happen.",
    example: "Completing the security training was a prerequisite for getting production access.",
  },
  {
    word: "Criterion",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A principle or standard by which something may be judged.",
    example: "Load time became the main criterion for approving the new homepage design.",
  },
  {
    word: "Parameter",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A limit or boundary that defines the scope of something.",
    example: "The redesign had to work within the parameter of a two-week deadline.",
  },
  {
    word: "Constraint",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "A limitation or restriction.",
    example: "Budget was the biggest constraint on which vendor the team could choose.",
  },
  {
    word: "Variable",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "An element, factor, or condition liable to change.",
    example: "Network latency was the one variable nobody had accounted for in testing.",
  },
  {
    word: "Correlation",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "A mutual relationship or connection between two or more things.",
    example: "There was a clear correlation between response time and customer churn.",
  },
  {
    word: "Causation",
    partOfSpeech: "noun",
    sentiment: "neutral",
    meaning: "The action of causing something; the relationship between cause and effect.",
    example: "The data showed correlation, but the team still had to prove causation.",
  },
  {
    word: "Synergy",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "The interaction of elements that produces a combined effect greater than the sum of their separate effects.",
    example: "Merging the two teams created real synergy between design and engineering.",
  },
  {
    word: "Alignment",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "Agreement or cooperation between people, groups, or things.",
    example: "The offsite was meant to get every department into alignment on next year's goals.",
  },
  {
    word: "Cohesion",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "The action or fact of forming a united whole.",
    example: "Regular stand-ups helped restore some cohesion to the newly merged team.",
  },
  {
    word: "Fragmentation",
    partOfSpeech: "noun",
    sentiment: "negative",
    meaning: "The process of breaking into small or separate parts.",
    example: "Fragmentation across five different tools made reporting a nightmare.",
  },
  {
    word: "Efficiency",
    partOfSpeech: "noun",
    sentiment: "positive",
    meaning: "The state of achieving maximum productivity with minimum wasted effort.",
    example: "The new pipeline improved efficiency enough to cut the build time in half.",
  },
  {
    word: "Optimize",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To make the best or most effective use of a situation or resource.",
    example: "The team spent a sprint just optimizing the checkout flow's load time.",
  },
  {
    word: "Expedite",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To make a process happen more quickly.",
    example: "Management asked legal to expedite the review so the deal could close by Friday.",
  },
  {
    word: "Curtail",
    partOfSpeech: "verb",
    sentiment: "negative",
    meaning: "To reduce in extent or quantity; to impose a restriction on.",
    example: "Travel budgets were curtailed for the rest of the year.",
  },
  {
    word: "Alleviate",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To make suffering, a deficiency, or a problem less severe.",
    example: "Adding a second server helped alleviate the load during peak hours.",
  },
  {
    word: "Exacerbate",
    partOfSpeech: "verb",
    sentiment: "negative",
    meaning: "To make a problem or situation worse.",
    example: "The rushed patch only exacerbated the very bug it was meant to fix.",
  },
  {
    word: "Undermine",
    partOfSpeech: "verb",
    sentiment: "negative",
    meaning: "To weaken or damage something gradually or subtly.",
    example: "Missed deadlines had started to undermine the client's confidence in the team.",
  },
  {
    word: "Corroborate",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To confirm or give support to a statement or finding.",
    example: "The second log file corroborated what the first engineer had already suspected.",
  },
  {
    word: "Refute",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To prove a statement or theory to be wrong.",
    example: "The benchmark results refuted the vendor's performance claims.",
  },
  {
    word: "Validate",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To check or prove the accuracy or worth of something.",
    example: "QA spent the extra day validating the fix against every reported case.",
  },
  {
    word: "Reiterate",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To say something again or a number of times for emphasis.",
    example: "She had to reiterate the deadline twice before the message actually landed.",
  },
  {
    word: "Elaborate",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To develop or present a theory or idea in further detail.",
    example: "He was asked to elaborate on why the estimate had doubled overnight.",
  },
  {
    word: "Clarify",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To make a statement or situation less confusing.",
    example: "One follow-up email was enough to clarify what the client actually needed.",
  },
  {
    word: "Deduce",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To arrive at a fact or conclusion by reasoning.",
    example: "From the timestamps alone, she could deduce which deploy had caused the crash.",
  },
  {
    word: "Infer",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To deduce or conclude something from evidence and reasoning rather than explicit statement.",
    example: "From the tone of the email, he inferred that the client wasn't happy.",
  },
  {
    word: "Presume",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To suppose that something is true without proof.",
    example: "Don't presume the fix worked just because the error stopped showing up locally.",
  },
  {
    word: "Deviate",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To depart from an established course or standard.",
    example: "The final design had to deviate slightly from the original spec to meet accessibility rules.",
  },
  {
    word: "Adhere",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To stick firmly to a rule, plan, or set of standards.",
    example: "New contributors are expected to adhere to the existing code style.",
  },
  {
    word: "Comply",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To act in accordance with a wish, command, or set of rules.",
    example: "Every vendor had to comply with the updated data-handling policy by year end.",
  },
  {
    word: "Contravene",
    partOfSpeech: "verb",
    sentiment: "negative",
    meaning: "To act in a way that conflicts with a rule or law.",
    example: "The workaround contravened the company's own data-retention policy.",
  },
  {
    word: "Delegate",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To entrust a task or responsibility to another person.",
    example: "She learned to delegate code reviews instead of doing every one herself.",
  },
  {
    word: "Escalate",
    partOfSpeech: "verb",
    sentiment: "negative",
    meaning: "To make a problem more serious, or to refer it to a higher authority.",
    example: "If the customer isn't satisfied, escalate the ticket to the account manager.",
  },
  {
    word: "Prioritize",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To designate or treat something as more important than other things.",
    example: "The backlog was reshuffled to prioritize the bug affecting the most users.",
  },
  {
    word: "Consolidate",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To combine a number of things into a single, more effective whole.",
    example: "The two dashboards were consolidated into one so nobody had to check both.",
  },
  {
    word: "Rectify",
    partOfSpeech: "verb",
    sentiment: "positive",
    meaning: "To put something right; to correct an error.",
    example: "The team worked through the weekend to rectify the billing mistake before it reached more customers.",
  },
  {
    word: "Revise",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To re-examine and make changes to something.",
    example: "The roadmap was revised twice before it matched what leadership actually wanted.",
  },
  {
    word: "Overhaul",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To take apart a system or process in order to examine and repair it thoroughly.",
    example: "The onboarding flow needed a full overhaul, not just a few small tweaks.",
  },
  {
    word: "Scrutinize",
    partOfSpeech: "verb",
    sentiment: "neutral",
    meaning: "To examine or inspect closely and thoroughly.",
    example: "Every line of the migration script was scrutinized before it touched production data.",
  },
];

/**
 * Deterministic day-of-year rotation so every visitor sees the same word on
 * a given day, cycling back to the start once the bank is exhausted.
 */
export function wordOfTheDay(date: Date = new Date()): WordEntry {
  const startOfYear = Date.UTC(date.getUTCFullYear(), 0, 0);
  const startOfDay = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate());
  const dayOfYear = Math.floor((startOfDay - startOfYear) / 86_400_000);
  return WORDS[dayOfYear % WORDS.length];
}
